name: Flake Check
on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "flake.nix"
      - "flake.lock"
  pull_request:
    paths:
      - "**.nix"
      - "flake.nix"
      - "flake.lock"
  workflow_dispatch: # Allows manual trigger
jobs:
  flake-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Nix flake checks
        run: nix flake check --all-systems
