name: Flake Build
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build-dev-shells:
    name: Build on ${{ matrix.system }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: |
          nix build
